import type { Metadata } from "next";
import "./globals.css";
import { sans, stylized } from "@/fonts";
import { UseLenis } from "@/utils/use-lenis";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sans.variable} ${stylized.variable} font-sans antialiased`}
      >
        <UseLenis />
        {children}
      </body>
    </html>
  );
}
